### ISSUE TITLE
Translate for other languages

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/rb-external-thumbnail#4]
The plugin has a translate file and ready for:
- [x] en_EN
- [x] de_DE
- [x] es_ES
- [x] fr_FR
- [x] hi_IN
- [x] hr_HR
- [x] it_IT
- [x] ja_JA
- [x] nl_NL
- [x] no_NO
- [x] ru_RU
- [x] pl_PL
- [x] pt_BR
- [x] sk_SK
- [x] tr_TR
- [x] zk_HK
- [ ] Any other languages are avaliable.

To trasnlate you must duplicate the .pot file and rename it to rb-external-thumbnail-lang_COUNTRY.po
Example: rb-external-thumbnail-pt_BR.po

pt_BR means Portuguese Brazil, but many languages don't have a country variation...
you'll have to fill in with your own language

Other way is the application: https://poedit.net/
But the first way is easy!

**Comment by Fahrenhei7** [comment]
there are msgid and msgstr identifiers. What I have to write for russian translate?

**Comment by SmuSmu** [comment]
Whats the naming convention for the file? I expect to translate msgstr and name the file in a special way? I will take care of german :-)

**Comment by SmuSmu** [comment]
I created a mo file with https://poedit.net/. Correct?

**Comment by fortrieb** [comment]
@SmuSmu no need to install this app. It's just a text file, lock at my pull request #6 .

**Comment by Fahrenhei7** [comment]
#8

**Comment by Fahrenhei7** [comment]
#8

**Comment by Fahrenhei7** [comment]
#8

**Comment by rodrigo-brito** [comment]
Hello guys!
To trasnlate you must duplicate the .pot file and rename it to rb-external-thumbnail-lang_COUNTRY.po
Example: rb-external-thumbnail-pt_BR.po
- pt_BR means Portuguese Brazil, but many languages don't have a country variation...
- you'll have to fill in with your own language

**Comment by rodrigo-brito** [comment]
Other way is the application: https://poedit.net/
But the first way is easy!

**Comment by ghost** [comment]
Add dutch translation file #10

**Comment by enriquegh** [comment]
added spanish translation file #11

**Comment by bSzala** [comment]
I will add Polish translation

**Comment by wahackr** [comment]
adding Traditional Chinese

**Comment by rafajaques** [comment]
I'll take French!

**Comment by rodrigo-brito** [comment]
Muito obrigado @rafajaques!

**Comment by jslirola** [comment]
I could improve some little errors of spanish translation, I'm native. Should I overwrite the line of "Last-Translator"? I'm not familiar with POT files.

**Comment by rodrigo-brito** [comment]
@jslirola Yes, you can overwrite the strings.

**Comment by wolframtheta** [comment]
If you want I can translate to Catalan :)

**Comment by rodrigo-brito** [comment]
Yes, You can @wolframtheta

**Comment by nayangupta824** [comment]
Added Hindi Translation (hi-IN)

**Comment by codegateau** [comment]
#30 Will add Malay translation (ms_MY) .

**Comment by hndr91** [comment]
I'll take Bahasa Indonesia
